"""Initial migration

Revision ID: e65edce0b27f
Revises: 
Create Date: 2026-04-24 14:32:01.795854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65edce0b27f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('factor_id', sa.String(length=36), nullable=False),
    sa.Column('standard', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('factor_value', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('grid_intensity_g_co2_kwh', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.String(length=10), nullable=True),
    sa.Column('radiative_forcing_multiplier', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('wtt_factor', sa.Numeric(precision=15, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('factor_id'),
    sa.UniqueConstraint('standard', 'category', 'subcategory', 'region', 'version')
    )
    op.create_index('idx_factors_lookup', 'emission_factors', ['category', 'subcategory', 'region', 'is_active'], unique=False)
    op.create_table('productions',
    sa.Column('production_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('budget_band', sa.String(length=50), nullable=True),
    sa.Column('runtime_min', sa.Integer(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('shoot_days', sa.Integer(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('cast_count', sa.Integer(), nullable=True),
    sa.Column('crew_count', sa.Integer(), nullable=True),
    sa.Column('vfx_intensity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('carbon_budget_tco2e', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('carbon_budget_source', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('production_id')
    )
    op.create_index('idx_productions_domain_status', 'productions', ['domain', 'status'], unique=False)
    op.create_table('activity_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('production_id', sa.String(length=36), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('kgco2e', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('kgco2e_wtt', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('confidence_tier', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('emission_factor_id', sa.String(length=36), nullable=True),
    sa.Column('emission_factor_version', sa.String(length=100), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('grid_region', sa.String(length=50), nullable=True),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calculation_method', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.factor_id'], ),
    sa.ForeignKeyConstraint(['production_id'], ['productions.production_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_events_confidence', 'activity_events', ['confidence_tier'], unique=False)
    op.create_index('idx_events_production', 'activity_events', ['production_id', 'category'], unique=False)
    op.create_index('idx_events_scope', 'activity_events', ['production_id', 'scope'], unique=False)
    op.create_table('documents',
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('production_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('s3_path', sa.Text(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('ocr_status', sa.String(length=50), nullable=True),
    sa.Column('extracted_raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('extracted_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('extracted_by_model', sa.String(length=100), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('linked_event_ids', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.production_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_index('idx_events_scope', table_name='activity_events')
    op.drop_index('idx_events_production', table_name='activity_events')
    op.drop_index('idx_events_confidence', table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index('idx_productions_domain_status', table_name='productions')
    op.drop_table('productions')
    op.drop_index('idx_factors_lookup', table_name='emission_factors')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
